Controllers/RentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Session;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Rentos.Data;
using Rentos.Models;
using Rentos.Models.RentViewModels;

namespace Rentos.Controllers
{
    public class RentsController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly RentosContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private static Rent _rent;
        public RentsController(RentosContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager,
            ApplicationDbContext applicationDbContext)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
            _applicationDbContext = applicationDbContext;
            _rent = new Rent();
        }

        // GET: Rents
        public IActionResult Index()
        {
            var rentList = new List<RentListViewModel>();
            foreach(var item in _context.Rent)
            {
                rentList.Add(new RentListViewModel()
                {
                    Car = _context.Car.Find(item.Car_CarId),
                    User = _applicationDbContext.ApplicationUser.Find(item.User_UserId),
                    Rent = item
                });
            }
            return View(rentList);
        }

        // GET: Rents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rent = await _context.Rent
                .SingleOrDefaultAsync(m => m.RentId == id);
            if (rent == null)
            {
                return NotFound();
            }

            return View(rent);
        }

        // GET: Cars
        public IActionResult FindCars()
        {
            var manufacturers = _context.Car.Select(c => c.Manufacturer).Distinct().ToList();
            manufacturers.Insert(0, "");

            var colors = _context.Car.Select(c => c.Color).Distinct().ToList();
            colors.Insert(0, "");

            ViewBag.Manufacturers = new SelectList(manufacturers);
            ViewBag.Colors = new SelectList(colors);

            return View("Create");
        }

        //Action result for ajax call
        //Used to dynamically show car models based on selected manufacturer
        [HttpPost]
        public ActionResult GetModelByManufacturer(string manufacturer)
        {
            var models = _context.Car.Where(c => c.Manufacturer == manufacturer).Select( m => m.Model).Distinct().ToList();
            SelectList modelsList = new SelectList(models);
            return Json(modelsList);
        }
        // POST: Rents/FindCARS
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        public IActionResult SearchResult(RentSearchViewModel rentSearch)
        {
            if (ModelState.IsValid)
            {
                
                var currentRents = _context.Rent.Where(r => 
                (
                ((DateTime.Compare(r.PickupDate,rentSearch.PickupDate) >= 0) && (DateTime.Compare(r.PickupDate,rentSearch.DropoffDate) <= 0))
                ||
                ((DateTime.Compare(r.DropoffDate,rentSearch.PickupDate) >= 0) && (DateTime.Compare(r.DropoffDate, rentSearch.DropoffDate) <= 0))
                ||
                ((DateTime.Compare(r.PickupDate, rentSearch.PickupDate) <= 0) && (DateTime.Compare(r.DropoffDate, rentSearch.DropoffDate) >= 0))
                )
                );
                var unavailableCars = new List<Car>();
                foreach (var item in currentRents)
                {
                    unavailableCars.Add(_context.Car.Find(item.Car_CarId));
                }

                var availableCars = _context.Car.ToList().Except(unavailableCars);

                #region Filters
                if (!String.IsNullOrEmpty(rentSearch.ManufacturerFilter))
                {
                    availableCars = availableCars.Where(c => c.Manufacturer == rentSearch.ManufacturerFilter);
                }

                if (!String.IsNullOrEmpty(rentSearch.MinPowerFilter))
                {
                    var power = Int32.Parse(rentSearch.MinPowerFilter);
                    availableCars = availableCars.Where(c => c.Power >= power);
                }
                if (!String.IsNullOrEmpty(rentSearch.MaxPriceFilter))
                {
                    var price = Int32.Parse(rentSearch.MaxPriceFilter);
                    availableCars = availableCars.Where(c => c.Price <= price);
                }
                if (!String.IsNullOrEmpty(rentSearch.ColorFilter))
                {
                    availableCars = availableCars.Where(c => c.Color == rentSearch.ColorFilter);
                }
                if (!String.IsNullOrEmpty(rentSearch.ModelFilter))
                {
                    availableCars = availableCars.Where(c => c.Model == rentSearch.ModelFilter);
                }
                #endregion

                var rentStr = JsonConvert.SerializeObject(new Rent() { DropoffDate = rentSearch.DropoffDate, PickupDate = rentSearch.PickupDate });
                HttpContext.Session.SetString("rent", rentStr);
                ViewBag.pickup = rentSearch.PickupDate;
                ViewBag.dropoff = rentSearch.DropoffDate;

                if(!availableCars.Any())
                {
                    TempData["statusMessage"] = "Sorry! No available vehicles meet the specified criteria!";
                    TempData["secondaryMessage"] = "Please try again.";
                    return RedirectToAction("FindCars");
                }
                else
                {
                    ViewBag.statusMessage = availableCars.Count() + " vehicle(s) found. Please select one to rent.";
                    ViewBag.secondaryMessage = "A standard 500DT precaution fee will be applied to all rent operations.";
                }
                return View("FindCars", availableCars); 
            }

            return View(rentSearch);
        }


        // GET: Rents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rent = await _context.Rent.SingleOrDefaultAsync(m => m.RentId == id);
            if (rent == null)
            {
                return NotFound();
            }
            ViewData["Car_CarId"] = new SelectList(_context.Car, "CarId", "CarId", rent.Car_CarId);
            ViewData["User_UserId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", rent.User_UserId);
            return View(rent);
        }

        // POST: Rents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RentId,Car_CarId,User_UserId,PickupDate,DropoffDate")] Rent rent)
        {
            if (id != rent.RentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currentRents = _context.Rent.Where(r => (
                ((DateTime.Compare(r.PickupDate, rent.PickupDate) >= 0) && (DateTime.Compare(r.PickupDate, rent.DropoffDate) <= 0))
                ||
                ((DateTime.Compare(r.DropoffDate, rent.PickupDate) >= 0) && (DateTime.Compare(r.DropoffDate, rent.DropoffDate) <= 0))
                ||
                ((DateTime.Compare(r.PickupDate, rent.PickupDate) <= 0) && (DateTime.Compare(r.DropoffDate, rent.DropoffDate) >= 0))
                ));
                    if(!currentRents.Any(c => c.Car_CarId == rent.Car_CarId))
                    { 
                    _context.Update(rent);
                    await _context.SaveChangesAsync();
                    }
                    else
                    {
                        ModelState.AddModelError("Unavailable", "Car is unavailable at the specified date range. Please try again.");
                        return View(rent);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentExists(rent.Car_CarId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Car_CarId"] = new SelectList(_context.Car, "CarId", "CarId", rent.Car_CarId);
            ViewData["User_UserId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", rent.User_UserId);
            return View(rent);
        }

        // GET: Rents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rent = await _context.Rent
                .SingleOrDefaultAsync(m => m.RentId == id);
            if (rent == null)
            {
                return NotFound();
            }

            return View(rent);
        }

        // POST: Rents/Delete/5

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
 
<html>
<head>
    <title>@ViewData["Title"] - Rentos</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="~/css/styles.min.css">
</head>
<body>
    <div>
        <div class="header-dark fixed-top">
            <nav class="navbar navbar-dark navbar-expand-md fixed-top">
                <div class="container">
                    <a class="navbar-brand" asp-controller="Rents" asp-action="FindCars">Rentos</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                         id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        </ul>
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <br />
    <br />
    <br />
    <br />
    <div class="overlay"></div>
    <div class="container container-fluid p-0">

        @RenderBody()
        <hr />

    </div>
    <div class="footer-basic">
        <footer>
            <p class="copyright">Rentos © 2018</p>
        </footer>
    </div>


    <environment include="Development">
        <script src="~/js/jquery.min.js"></script>
        <script src="~/lib/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>