Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Rentos.Models
{
    public class Car
    {
        public Car() => Rents = new List<Rent>();

        public int CarId { get; set; }

        public string Manufacturer { get; set; }

        public string Model { get; set; }

        [Display(Name="Registration number")]
        public string RegistrationNumber { get; set; }

        public string Color { get; set; }

        public string Picture { get; set; }

        public int Mileage { get; set; }

        public int Power { get; set; }

        public int Price { get; set; }

        [Display(Name ="Car is available.")]
        public Boolean IsAvailable { get; set; }

        public virtual ICollection<Rent> Rents { get; set; }
    }
}

Models/CarViewModels/CarViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Rentos.Models.CarViewModels
{
    public class CarViewModel
    {

        public int CarId { get; set; }

        public string Manufacturer { get; set; }

        public string Model { get; set; }

        [Display(Name = "Registration number")]
        public string RegistrationNumber { get; set; }

        public string Color { get; set; }

        public int Mileage { get; set; }

        public int Power { get; set; }

        public int Price { get; set; }

        [Display(Name = "Car is available.")]
        public Boolean IsAvailable { get; set; }
    }
}

Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rentos.Models;
using Rentos.Models.CarViewModels;

namespace Rentos.Controllers
{
    [Authorize(Roles = "admin")]
    public class CarsController : Controller
    {

        private readonly RentosContext _context;

        public CarsController(RentosContext context)
        {
            _context = context;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
            return View(await _context.Car.ToListAsync());
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .SingleOrDefaultAsync(m => m.CarId == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CarId,Manufacturer,Model,RegistrationNumber,Color,Mileage,Power,Price,IsAvailable")] Car car)
        {
            if (ModelState.IsValid)
            {
                var filePath = Path.GetTempFileName();

                var file = HttpContext.Request.Form.Files;

                if (file.First().Length > 0)
                {
                    using (var stream = new FileStream("wwwroot/images/cars/" + file.First().FileName, FileMode.Create))
                    {
                        await file.First().CopyToAsync(stream);
                        car.Picture = file.First().FileName;
                    }
                }

                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car.SingleOrDefaultAsync(m => m.CarId == id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarId,Manufacturer,Model,RegistrationNumber,Picture,Color,Mileage,Power,Price,IsAvailable")] Car car)
        {
            if (id != car.CarId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var file = HttpContext.Request.Form.Files;

                if (file.First().Length > 0)
                {
                    using (var stream = new FileStream("wwwroot/images/cars/" + file.First().FileName, FileMode.Create))
                    {
                        await file.First().CopyToAsync(stream);
                        car.Picture = file.First().FileName;
                    }
                }
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.CarId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .SingleOrDefaultAsync(m => m.CarId == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Car.SingleOrDefaultAsync(m => m.CarId == id);
            _context.Car.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Car.Any(e => e.CarId == id);
        }
    }
}

Views/Cars/Create.cshtml
@model Rentos.Models.Car

@{
    ViewData["Title"] = "Add new car";
}

<h2 class="text-center text-muted">Add new car</h2>

<hr />
    <div class="row justify-content-center">
        <div class="card bg-dark text-white col-lg-7 pl-5 pr-5 pb-3 pt-3">
            <div class="card-header">
                <h4 class="text-center">
                    Please fill in the information below.
                </h4>
            </div>
            <div class="card bg-dark text-info text-center">
                <img id="carPic" src="#" alt="Upload a picture to see the preview here." class="img-thumbnail img-fluid bg-dark" />
            </div>
            <form asp-action="Create" asp-controller="Cars" enctype="multipart/form-data">
                <div class="row justify-content-center">
                    <div class="form-group m-2">
                        <label asp-for="Manufacturer" class="control-label"></label>
                        <input asp-for="Manufacturer" class="form-control" />
                        <span asp-validation-for="Manufacturer" class="text-danger"></span>
                    </div>
                    <div class="form-group m-2">
                        <label asp-for="Model" class="control-label"></label>
                        <input asp-for="Model" class="form-control" />
                        <span asp-validation-for="Model" class="text-danger"></span>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="form-group m-2">
                        <label asp-for="RegistrationNumber" class="control-label"></label>
                        <input asp-for="RegistrationNumber" class="form-control" />
                        <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group m-2">
                        <label asp-for="Color" class="control-label"></label>
                        <input asp-for="Color" class="form-control" />
                        <span asp-validation-for="Color" class="text-danger"></span>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="form-group m-2">
                        <label asp-for="Mileage" class="control-label"></label>
                        <input asp-for="Mileage" class="form-control" />
                        <span asp-validation-for="Mileage" class="text-danger"></span>
                    </div>

                    <div class="form-group m-2">
                        <label asp-for="Power" class="control-label"></label>
                        <input asp-for="Power" class="form-control" />
                        <span asp-validation-for="Power" class="text-danger"></span>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="form-group m-2">
                        <label asp-for="Price" class="control-label"></label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="form-group m-2">
                        <label asp-for="Picture" class="control-label"></label>
                        <label class="btn btn-info btn-file">
                            Browse <input asp-for="Picture" type="file" style="display: none;">
                        </label>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="form-group m-2">
                        <div class="checkbox">
                            <label>
                                <input asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                            </label>
                        </div>
                    </div>

                </div>
                <div class="form-group justify-content-center">
                    <a asp-action="Index" class="btn btn-info">Back</a>
                    <input type="submit" value="Save" class="btn btn-info pull-right" />
                </div>
            </form>

        </div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#carPic').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#Picture").change(function () {
        readURL(this);
    });
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Cars/Delete.cshtml
@model Rentos.Models.Car

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mileage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mileage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Power)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Power)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CarId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Cars/Details.cshtml
@model Rentos.Models.Car

@{
    ViewData["Title"] = "Details";

    var carPicture = "/images/cars/" + Model.Picture;
}


<h2 class="text-center text-muted">Car details</h2>
<hr />
<div class="container">

    <div class="row">
        <img src="@carPicture" class="img-responsive pull-left" style="height: 444px; width: 592px;" />
        <div class="col-md-5">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td><b>@Html.DisplayNameFor(model => model.Manufacturer)</b></td>
                        <td>@Html.DisplayFor(model => model.Manufacturer)</td>
                    </tr>
                    <tr>
                        <td> <b>@Html.DisplayNameFor(model => model.Model)</b></td>
                        <td> @Html.DisplayFor(model => model.Model)</td>
                    </tr>
                    <tr>
                        <td><b> @Html.DisplayNameFor(model => model.RegistrationNumber)</b></td>
                        <td> @Html.DisplayFor(model => model.RegistrationNumber)</td>
                    </tr>
                    <tr>
                        <td><b> @Html.DisplayNameFor(model => model.Color)</b></td>
                        <td> @Html.DisplayFor(model => model.Color)</td>
                    </tr>
                    <tr>
                        <td><b> @Html.DisplayNameFor(model => model.Mileage)</b></td>
                        <td> @Html.DisplayFor(model => model.Mileage)</td>
                    </tr>
                    <tr>
                        <td><b> @Html.DisplayNameFor(model => model.Power)</b></td>
                        <td> @Html.DisplayFor(model => model.Power)</td>
                    </tr>
                    <tr>
                        <td> <b>@Html.DisplayNameFor(model => model.Price)</b></td>
                        <td> @Html.DisplayFor(model => model.Price)</td>
                    </tr>
                </tbody>
            </table>
            <div>
                <a asp-action="Edit" asp-route-id="@Model.CarId" class="btn btn-info">Edit</a> 
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</div>

Views/Cars/Edit.cshtml
@model Rentos.Models.Car

@{
    ViewData["Title"] = "Edit car information";
}

<h2 class="text-center text-muted">Edit car information</h2>
<hr />
<div class="row justify-content-center">
    <div class="card bg-dark text-white col-lg-7 pl-5 pr-5 pb-3 pt-3">
        <div class="card-header">
            <h4 class="text-center">
                Please fill in the information below.
            </h4>
        </div>
        <div class="card bg-dark text-info text-center">
            <img id="carPic" src="#" alt="Upload a picture to see the preview here." class="img-thumbnail img-fluid bg-dark" />
        </div>
        <form asp-action="Edit" asp-controller="Cars" enctype="multipart/form-data">
            <input type="hidden" asp-for="CarId" />
            <input type="hidden" asp-for="Picture" />
            <div class="row justify-content-center">
                <div class="form-group m-2">
                    <label asp-for="Manufacturer" class="control-label"></label>
                    <input asp-for="Manufacturer" class="form-control" />
                    <span asp-validation-for="Manufacturer" class="text-danger"></span>
                </div>
                <div class="form-group m-2">
                    <label asp-for="Model" class="control-label"></label>
                    <input asp-for="Model" class="form-control" />
                    <span asp-validation-for="Model" class="text-danger"></span>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="form-group m-2">
                    <label asp-for="RegistrationNumber" class="control-label"></label>
                    <input asp-for="RegistrationNumber" class="form-control" />
                    <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
                </div>
                <div class="form-group m-2">
                    <label asp-for="Color" class="control-label"></label>
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="form-group m-2">
                    <label asp-for="Mileage" class="control-label"></label>
                    <input asp-for="Mileage" class="form-control" />
                    <span asp-validation-for="Mileage" class="text-danger"></span>
                </div>

                <div class="form-group m-2">
                    <label asp-for="Power" class="control-label"></label>
                    <input asp-for="Power" class="form-control" />
                    <span asp-validation-for="Power" class="text-danger"></span>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="form-group m-2">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="form-group m-2">
                    <label asp-for="Picture" class="control-label"></label>
                    <label class="btn btn-info btn-file">
                        Browse <input asp-for="Picture" type="file" style="display: none;">
                    </label>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="form-group m-2">
                    <div class="checkbox">
                        <label>
                            <input asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                        </label>
                    </div>
                </div>

            </div>
            <div class="form-group justify-content-center">
                <a asp-action="Index" class="btn btn-info">Back</a>
                <input type="submit" value="Save" class="btn btn-info pull-right" />
            </div>
        </form>
    </div>
</div>

<div>
    
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#carPic').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#Picture").change(function () {
        readURL(this);
    });
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Cars/Index.cshtml
@model IEnumerable<Rentos.Models.Car>

@{
    ViewData["Title"] = "Index";
}

<h2>Currently owned cars</h2>

<p>
    <a asp-action="Create">Add new car</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Manufacturer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Model)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RegistrationNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsAvailable)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Manufacturer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAvailable)
            </td>
            <td class="col-md-5 d-flex justify-content-center">
                <a asp-action="Edit" asp-route-id="@item.CarId" class="btn btn-warning ml-3 mr-3">Edit</a> 
                <a asp-action="Details" asp-route-id="@item.CarId" class="btn btn-info mr-3">Details</a> 
                <form asp-action="Delete">
                    <input type="hidden" name="id" value="@item.CarId" />
                    <input onclick="return confirm('Are you sure you want to remove this car?');" type="submit" value="Delete" class="btn btn-danger" /> 
                </form>
            </td>
        </tr>
}
    </tbody>
</table>